# RELEASE VERSION
VERSION = "DEV"

# COLOURS
GRAY = "\033[90m"
RESET = "\033[0m"
DIM = "\033[2m"

# ALLOWED
STATUSES = ["REGISTERED", "DRAFT", "PENDING", "ACCEPTED", "APPROVED", "SUPERSEDED", "WITHDRAWN"]
DEFAULT_STATUS = "REGISTERED"
CI_TYPES = ["DRAWING", "ENGINEERING REPORT", "INSTRUCTION", "DESIGN MASTER APPROVAL"]
